version: "3.1"
services:

  mysql:
    image: mysql:5.7
    container_name: db
    working_dir: /application/src
    volumes:
      - ./database/files:/var/lib/mysql
      - ./database/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=soc
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"